import type { Metadata } from "next"
import "./style.css"

import Header from "./Header"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Header />
        </header>
        <div className="main">{children}</div>
      </body>
    </html>
  )
}
